# Generated by Django 6.0.3 on 2026-04-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=10, unique=True)),
                ('aadhaar', models.CharField(max_length=12, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('credit_score', models.IntegerField(default=750)),
            ],
        ),
    ]
